In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
plt.figure(figsize=(100,10))
data = pd.read_csv('Headbrain.csv')
print(data.shape)
data.head()

(237, 4)


Gender  Age Range  Head size  Brain Weights
0       1          1       4512           1530
1       1          1       3738           1297
2       1          1       4261           1335
3       1          1       3777           1282
4       1          1       4177           1590

<Figure size 7200x720 with 0 Axes>

In [6]:
x=data['Head size'].values
y=data['Brain Weights'].values

mean_x=np.mean(x)
mean_y=np.mean(y)
length = len(x)

numer = 0
denom = 0
for i in range(length):
    numer += (x[i] - mean_x)*(y[i] - mean_y)
    denom += (x[i] - mean_x)**2
m = numer/denom
c = mean_y-(m*mean_x)
print(m,c)

0.26342933948939945 325.57342104944223


In [7]:
y_pred = []
for i in x:
    y_pred.append(m*x+c)

In [8]:
y

array([1530, 1297, 1335, 1282, 1590, 1300, 1400, 1255, 1355, 1375, 1340,
       1380, 1355, 1522, 1208, 1405, 1358, 1292, 1340, 1400, 1357, 1287,
       1275, 1270, 1635, 1505, 1490, 1485, 1310, 1420, 1318, 1432, 1364,
       1405, 1432, 1207, 1375, 1350, 1236, 1250, 1350, 1320, 1525, 1570,
       1340, 1422, 1506, 1215, 1311, 1300, 1224, 1350, 1335, 1390, 1400,
       1225, 1310, 1560, 1330, 1222, 1415, 1175, 1330, 1485, 1470, 1135,
       1310, 1154, 1510, 1415, 1468, 1390, 1380, 1432, 1240, 1195, 1225,
       1188, 1252, 1315, 1245, 1430, 1279, 1245, 1309, 1412, 1120, 1220,
       1280, 1440, 1370, 1192, 1230, 1346, 1290, 1165, 1240, 1132, 1242,
       1270, 1218, 1430, 1588, 1320, 1290, 1260, 1425, 1226, 1360, 1620,
       1310, 1250, 1295, 1290, 1290, 1275, 1250, 1270, 1362, 1300, 1173,
       1256, 1440, 1180, 1306, 1350, 1125, 1165, 1312, 1300, 1270, 1335,
       1450, 1310, 1027, 1235, 1260, 1165, 1080, 1127, 1270, 1252, 1200,
       1290, 1334, 1380, 1140, 1243, 1340, 1168, 13

In [9]:
x

array([4512, 3738, 4261, 3777, 4177, 3585, 3785, 3559, 3613, 3982, 3443,
       3993, 3640, 4208, 3832, 3876, 3497, 3466, 3095, 4424, 3878, 4046,
       3804, 3710, 4747, 4423, 4036, 4022, 3454, 4175, 3787, 3796, 4103,
       4161, 4158, 3814, 3527, 3748, 3334, 3492, 3962, 3505, 4315, 3804,
       3863, 4034, 4308, 3165, 3641, 3644, 3891, 3793, 4270, 4063, 4012,
       3458, 3890, 4166, 3935, 3669, 3866, 3393, 4442, 4253, 3727, 3329,
       3415, 3372, 4430, 4381, 4008, 3858, 4121, 4057, 3824, 3394, 3558,
       3362, 3930, 3835, 3830, 3856, 3249, 3577, 3933, 3850, 3309, 3406,
       3506, 3907, 4160, 3318, 3662, 3899, 3700, 3779, 3473, 3490, 3654,
       3478, 3495, 3834, 3876, 3661, 3618, 3648, 4032, 3399, 3916, 4430,
       3695, 3524, 3571, 3594, 3383, 3499, 3589, 3900, 4114, 3937, 3399,
       4200, 4488, 3614, 4051, 3782, 3391, 3124, 4053, 3582, 3666, 3532,
       4046, 3667, 2857, 3436, 3791, 3302, 3104, 3171, 3572, 3530, 3175,
       3438, 3903, 3899, 3401, 3267, 3451, 3090, 34

In [10]:
y_pred

[array([1514.16660083, 1310.27229206, 1448.04583661, 1320.5460363 ,
        1425.9177721 , 1269.96760312, 1322.65347102, 1263.11844029,
        1277.34362462, 1374.5490509 , 1232.56063691, 1377.44677363,
        1284.45621679, 1434.08408162, 1335.03464997, 1346.62554091,
        1246.78582124, 1238.61951172, 1140.88722677, 1490.98481895,
        1347.15239959, 1391.40852862, 1327.65862847, 1302.89627056,
        1576.07249561, 1490.72138961, 1388.77423523, 1385.08622448,
        1235.45835965, 1425.39091342, 1323.1803297 , 1325.55119375,
        1406.42400097, 1421.70290266, 1420.91261465, 1330.29292186,
        1254.68870143, 1312.90658546, 1203.84683891, 1245.46867455,
        1369.28046411, 1248.89325596, 1462.27102095, 1327.65862847,
        1343.2009595 , 1388.24737655, 1460.42701557, 1159.32728053,
        1284.71964613, 1285.50993415, 1350.576981  , 1324.76090573,
        1450.41670067, 1395.88682739, 1382.45193108, 1236.512077  ,
        1350.31355166, 1423.02004936, 1362.16787

In [17]:
num=0
den=0
for i,j in zip(y_pred,y):
    num += (i - mean_y)**2
    den += (j - mean_y)**2
R_square=num/denom
print(R_square)

[3.70969989e+00 5.20569300e-02 1.89185640e+00 9.84157776e-02
 1.41890904e+00 1.15500524e-02 1.09734663e-01 2.70623924e-02
 2.12046386e-03 5.82801885e-01 1.75537438e-01 6.20227062e-01
 1.73725945e-04 1.58554273e+00 1.88672583e-01 2.81839862e-01
 9.03085828e-02 1.35805178e-01 1.39799407e+00 3.00334247e+00
 2.86517458e-01 8.16871266e-01 1.39085660e-01 2.78012947e-02
 5.96126340e+00 2.99574397e+00 7.77699351e-01 7.24475560e-01
 1.55899846e-01 1.40847608e+00 1.12660627e-01 1.26303874e-01
 1.05852888e+00 1.33652331e+00 1.32135027e+00 1.55929084e-01
 5.50858996e-02 6.25482833e-02 4.33071369e-01 9.70211606e-02
 5.17739657e-01 8.00689245e-02 2.23175432e+00 1.39085660e-01
 2.52373859e-01 7.69980460e-01 2.18611027e+00 1.05845270e+00
 2.36365436e-04 4.82030007e-04 3.17860209e-01 1.21669506e-01
 1.94655712e+00 8.85672310e-01 6.87613489e-01 1.49047633e-01
 3.15391482e-01 1.36200418e+00 4.36012299e-01 5.89775714e-03
 2.59029341e-01 2.79476353e-01 3.14176133e+00 1.84388799e+00
 4.16280537e-02 4.476277

In [14]:
R_square

NameError: name 'r_square' is not defined

In [15]:
R_square

array([3.70969989e+00, 5.20569300e-02, 1.89185640e+00, 9.84157776e-02,
       1.41890904e+00, 1.15500524e-02, 1.09734663e-01, 2.70623924e-02,
       2.12046386e-03, 5.82801885e-01, 1.75537438e-01, 6.20227062e-01,
       1.73725945e-04, 1.58554273e+00, 1.88672583e-01, 2.81839862e-01,
       9.03085828e-02, 1.35805178e-01, 1.39799407e+00, 3.00334247e+00,
       2.86517458e-01, 8.16871266e-01, 1.39085660e-01, 2.78012947e-02,
       5.96126340e+00, 2.99574397e+00, 7.77699351e-01, 7.24475560e-01,
       1.55899846e-01, 1.40847608e+00, 1.12660627e-01, 1.26303874e-01,
       1.05852888e+00, 1.33652331e+00, 1.32135027e+00, 1.55929084e-01,
       5.50858996e-02, 6.25482833e-02, 4.33071369e-01, 9.70211606e-02,
       5.17739657e-01, 8.00689245e-02, 2.23175432e+00, 1.39085660e-01,
       2.52373859e-01, 7.69980460e-01, 2.18611027e+00, 1.05845270e+00,
       2.36365436e-04, 4.82030007e-04, 3.17860209e-01, 1.21669506e-01,
       1.94655712e+00, 8.85672310e-01, 6.87613489e-01, 1.49047633e-01,
      

In [ ]:
import pnda