In [1]:
list1=["Sunday","Monday","Tuesday","Wednesday","Thrusday","Friday","Saturday"]
list2=[x[:3] for x in list1]
print(list2)

['Sun', 'Mon', 'Tue', 'Wed', 'Thr', 'Fri', 'Sat']


In [3]:
#Creating tuples
tuple1=("Sachin","Sourav","Dhoni")
print(tuple1[0])
for x in tuple1:
    print(x)

Sachin
Sachin
Sourav
Dhoni


In [5]:
tup1=('physics','chemistry',1997,2000)
tup2=(1,2,3,4,5,6,7)
print("tup1[0]: ",tup1[0])
print("tup2[1:5]: ",tup2[1:5])

tup1[0]:  physics
tup2[1:5]:  (2, 3, 4, 5)


In [6]:
import numpy as np
#1D array
arr1=np.array([1,2,3])
print(arr1)
print(type(arr1))
print(arr1.dtype)
print(arr1[0])

[1 2 3]
<class 'numpy.ndarray'>
int32
1


In [8]:
#nD array
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)
print(arr2[0,1])
print(arr2.ndim)

[[1 2 3]
 [4 5 6]]
2
2


In [9]:
arr2=np.array([(9),(2)])
print(arr2)
print(arr2.ndim)
#print(arr2[0,2])
arr2=np.array([(9,),(2,)])
print(arr2)
print(arr2.ndim)

[9 2]
1
[[9]
 [2]]
2


In [10]:
import numpy as np
#Data types
arr3=np.array([9,2],dtype=float)
print(arr3)
print(arr3.dtype)

[9. 2.]
float64


In [11]:
#shape-returns tupke consisting of array dimensions
arr1=np.array([[10,20],[30,40],[30,40]])
print("array shape is:",arr1.shape)
print("array is:",arr1)

array shape is: (3, 2)
array is: [[10 20]
 [30 40]
 [30 40]]


In [12]:
#resizes the shape
arr1=np.array([[10,20,40],[50,30,40]])
print("Array shape is :",arr1.shape)
arr1.shape=(3,2)
print("Array shape is :",arr1.shape)
print("Array is :",arr1)

Array shape is : (2, 3)
Array shape is : (3, 2)
Array is : [[10 20]
 [40 50]
 [30 40]]


In [13]:
#resizes the shape
arr2=np.array([[10,20,30,40],[50,30,40,80]])
b=arr2.reshape(4,2)
print("Array shape is:",arr2.shape)
print("Array is:",b)

Array shape is: (2, 4)
Array is: [[10 20]
 [30 40]
 [50 30]
 [40 80]]


In [16]:
arr2=np.empty([3,2],dtype=int)
print("Filled with random values:",arr2)#filled with random values

arr3=np.zeros([3,2])
print("Filled with 0 floats:",arr3)#default datatype is float

arr4=np.zeros([3,2],dtype=int)
print("Filled with 0 ints:",arr4)

arr5=np.ones([3,2],dtype=int)
print("Filled with 1 ints:",arr5)

Filled with random values: [[1 1]
 [1 1]
 [1 1]]
Filled with 0 floats: [[0. 0.]
 [0. 0.]
 [0. 0.]]
Filled with 0 ints: [[0 0]
 [0 0]
 [0 0]]
Filled with 1 ints: [[1 1]
 [1 1]
 [1 1]]


In [17]:
#Create an ndarray from a list
list1=[(1,2,3),(4,5,6)]
arr4=np.array(list1)
print("Dimension of array:",arr4.ndim)
print("Array from List of tuples:",arr4)

Dimension of array: 2
Array from List of tuples: [[1 2 3]
 [4 5 6]]


import numpy as 

In [6]:
import numpy as np
arr1=np.arange(10)#upper bound not included
print(arr1)
arr2=np.arange(10,dtype=float)
print(arr2)

arr3=np.arange(2,10,2)
print(arr3)#start,stop,step

#linespace--instead of step, the no. of inteval is specified.
arr4=np.linspace(2,10,4)#endpoint is to included the upper bound or not
print("Upper bound included: ",arr4)

arr4=np.linspace(2,10,3,endpoint=False,dtype=int)
print("upper bound not included",arr4)

[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[2 4 6 8]
Upper bound included:  [ 2.          4.66666667  7.33333333 10.        ]
upper not included [2 4 7]


In [19]:

arr1=np.arange(10)

print("2.After slicing:",arr1[2:9:1])
print("3.After slicing:",arr1[2:])

#slicing for nd array
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2[:,1:])


2.After slicing: [2 3 4 5 6 7 8]
3.After slicing: [2 3 4 5 6 7 8 9]
[[2 3]
 [5 6]
 [8 9]]


In [12]:
#using ellipsis- means will consider all the list
arr4=np.array([[1,2,3,4],[4,5,6,10],[7,8,9,11]])
print(arr4[...,1])
print(arr4[2,...])
print(arr4[...,1:])

[2 5 8]
[ 7  8  9 11]
[[ 2  3  4]
 [ 5  6 10]
 [ 8  9 11]]


In [14]:
arr5=np.array([[1,2,3],[4,5,6],[7,8,9]])
y=arr5[[0,1,2],[1,0,2]] #(0,1),(1,0),(2,2)
print("8.After Slicing:",y)

8.After Slicing: [2 4 9]


In [15]:
#Broadcasting when operations of multiple arrays with shape
arr7=np.array([[10,20,30],[2,3,4]])
arr8=np.array([[40,30,20],[7,6,5]])
print("Multiplication on arrays of same shape:",arr7*arr8)

#Smaller array are broadcasted to larger array

arr8=np.array([[1,1,1],[20,30,40],[50,60,70]])
arr9=np.array([1,2,3])
print("Array after addition",arr8+arr9)

Multiplication on arrays of same shape: [[400 600 600]
 [ 14  18  20]]
Array after addition [[ 2  3  4]
 [21 32 43]
 [51 62 73]]


In [16]:
#transposing array and then iterating
tempdeftransposed=arr1.T
print("4. Transposed array:",tempdeftransposed)

4. Transposed array: [0 1 2 3 4 5 6 7 8 9]


In [20]:
#Concatenate
arr1=np.array([[2,3],[4,5]])
arr2=np.array([[6,7],[8,9]])
resarr=np.concatenate((arr1,arr2))#default axis=0
print("Concatenate along 0 axis:",resarr)
resarr=np.concatenate((arr1,arr2),axis=1)
print("Concatenate along 1 axis:",resarr)

Concatenate along 0 axis: [[2 3]
 [4 5]
 [6 7]
 [8 9]]
Concatenate along 1 axis: [[2 3 6 7]
 [4 5 8 9]]


In [23]:
#Split
arr3=np.arange(9)
print("Whole array:",arr3)
arr4=np.split(arr3,3)
print("After splitting in 3 equal sized axis:",arr4)

Whole array: [0 1 2 3 4 5 6 7 8]
After splitting in 3 equal sized axis: [array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [24]:
#Append elements
arr4=np.arange(9)
arr4=arr4.reshape(3,3)
print("Before appending:",arr4)
arr5=np.append(arr4,[10,11,12])
print("After appending:",arr5)
arr6=np.append(arr4,[[10,11,12],[13,14,15],[16,17,18]],axis=1)
print("Appended at axis 1:",arr6)
arr6=np.append(arr4,[[10,11,12]],axis=0)
print("Appended at 0 axis:",arr6)

Before appending: [[0 1 2]
 [3 4 5]
 [6 7 8]]
After appending: [ 0  1  2  3  4  5  6  7  8 10 11 12]
Appended at axis 1: [[ 0  1  2 10 11 12]
 [ 3  4  5 13 14 15]
 [ 6  7  8 16 17 18]]
Appended at 0 axis: [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [10 11 12]]


In [26]:
#insert at specific location
arr4=np.arange(9)
arr4=arr4.reshape(3,3)
print("Arr4",arr4)
arr7=np.insert(arr4,3,199)
print("Axis parameter not passed hence flattend:",arr7)
arr8=np.insert(arr4,3,[11],axis=0)
print("Inserted at 3rd index in 0 axis:",arr8)
arr9=np.insert(arr4,3,[290],axis=1)
print("Inserted at 3rd index in 1 axis:",arr9)

Arr4 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Axis parameter not passed hence flattend: [  0   1   2 199   3   4   5   6   7   8]
Inserted at 3rd index in 0 axis: [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [11 11 11]]
Inserted at 3rd index in 1 axis: [[  0   1   2 290]
 [  3   4   5 290]
 [  6   7   8 290]]


In [4]:
#Remove
import numpy as np
arr4=np.arange(9)
arr4=arr4.reshape(3,3)
arr10=np.delete(arr4,3)
print("Array flattend before deleting as axis parameter not passed:",arr10)
arr11=np.delete(arr4,2,axis=0)
print("Element deleted along 0 axis:",arr11)
print(arr4)
arr11=np.delete(arr4,2,axis=1)
print("Element deleted along 1 axis:",arr11)
print(arr4)

Array flattend before deleting as axis parameter not passed: [0 1 2 4 5 6 7 8]
Element deleted along 0 axis: [[0 1 2]
 [3 4 5]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Element deleted along 1 axis: [[0 1]
 [3 4]
 [6 7]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [5]:
#methods::np.add(arr,arr),np.subtract(arr,arr),np.multiply(arr,arr),np.divide(arr,arr),np.power(x,y),np.median(arr3.axis=0)

In [22]:
#sorting according to 
arr1=np.array([[12,14,17],[2,5,8],[15,20,21]])
arr2=np.mean(arr1,axis=1)
arr2=np.sort(arr2)
for i in arr2:
    for j in arr1:
        if np.mean(j)==i:
            print(j)

[2 5 8]
[12 14 17]
[15 20 21]


In [23]:
import numpy as np
import pandas as pd
#Series is a single dimensional labelled array, can hold any type
ser1=pd.Series([1,2,3])
print("the series is :\n",ser1)
arr1=np.array([1,2,3])
ser2=pd.Series(arr1)
print(ser2)

the series is :
 0    1
1    2
2    3
dtype: int64
0    1
1    2
2    3
dtype: int32


In [24]:
arr2=np.array([1,2,3])
ser3=pd.Series(arr2, index=['a','b','c'])
print("the series from ndarray is :\n",ser3)

the series from ndarray is :
 a    1
b    2
c    3
dtype: int32


In [25]:
dict1={'a':10,'b':20,'c':30}
ser3=pd.Series(dict1)
print("series from dictionary in the same order :",ser3)

series from dictionary in the same order : a    10
b    20
c    30
dtype: int64


In [26]:
dict1={'a':10,'b':20,'c':30}
ser4=pd.Series(dict1,index=['b','a','c'])
print(ser4)

b    20
a    10
c    30
dtype: int64


In [27]:
arr3=np.arange(0,4)
ser7=pd.Series(arr3,index=['a','b','c','d'])
print("the 2nd element is th series is :",ser7[1])
print("last 3 element of the series :",ser7[-3:])
print(ser7[-3:])

the 2nd element is th series is : 1
last 3 element of the series : b    1
c    2
d    3
dtype: int32
b    1
c    2
d    3
dtype: int32


In [28]:
df1=pd.DataFrame()
print("empty df :",df1)

empty df : Empty DataFrame
Columns: []
Index: []


In [29]:
list1=[1,2,3,4]
df2=pd.DataFrame(list1)
print(df2)

   0
0  1
1  2
2  3
3  4


In [30]:
list2=[[1,2,3],[4,5,6],[7,8,9]]
df3=pd.DataFrame(list2)
print(df3)

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9


In [37]:
#Create df from list of lists with defined column names  
list3=[['sachin',10000],['msd',20000],['virat',5000]]
df4=pd.DataFrame(list3,columns=['cricketer','runs'])
#print("df from list of lists:\n,df4")
#df4["cricketer"].describe()
#print(df4.dtypes)
#df.info()
df4["runs"].describe()
#df4["Cricketer"].describe()

count        3.000000
mean     11666.666667
std       7637.626158
min       5000.000000
25%       7500.000000
50%      10000.000000
75%      15000.000000
max      20000.000000
Name: runs, dtype: float64

In [32]:
dict1={"name":['sachin','sourav','sachin'],"runs":[10000,20000,40000]}
df5=pd.DataFrame(dict1)
print(df5)

     name   runs
0  sachin  10000
1  sourav  20000
2  sachin  40000


In [33]:
dict1={"name":['sachin','sourav','sachin'],"runs":[10000,20000,40000]}
df5=pd.DataFrame(dict1,index=["rank1","rank2","rank3"])
print(df5)

         name   runs
rank1  sachin  10000
rank2  sourav  20000
rank3  sachin  40000


In [34]:
list3=[{"name":"sachin","run":20000},{"name":"sachin","run":20000,"address":"kolkata"}]
df6=pd.DataFrame(list3)
print(df6)

   address    name    run
0      NaN  sachin  20000
1  kolkata  sachin  20000


In [35]:
list4=[{"a":1,"b":2},{"a":4,"b":5},{"c":10}]
df7=pd.DtaFrame(List4)


AttributeError: module 'pandas' has no attribute 'DtaFrame'