In [1]:
print("{1} earns a salary of Rs.{0}".format(10000,"Sachin"))

Sachin earns a salary of Rs.10000


In [7]:
var1,var2,var3=100,100.0,"Hello World"
print(var1)
print(var2)
print(var3,"\n")

100
100.0
Hello World 



In [6]:
var1,var2,var3=100,100.0,"Hello World"
print(var1)
print(var2)
print(var3,"\n")

print(type(var1))
print(type(var2))
print(type(var3))



100
100.0
Hello World 

<class 'int'>
<class 'float'>
<class 'str'>


In [1]:
a,b=10,11
print("a is greater than b") if a > b else print("a is equal to b") if a==b else print("b is greater than a")

b is greater than a


In [1]:
#while loop
var=1
while var<10:
    print(var)
    if(var==3):
        break
    var+=1     

1
2
3


In [2]:
#for loop
for i in(1,2,3):
    print(i)

1
2
3


In [3]:
#for in range method with step
#upper bound is exclude here
for i in range(1,20,2):
    print(i)

1
3
5
7
9
11
13
15
17
19


In [50]:
#for in range method with reverse step
#upper bound is excluded here
for i in range(20,1,-2):
    print(i)


20
18
16
14
12
10
8
6
4
2


In [6]:
#math functions
import math
c=9.7
#var='a'

print("The ceiling value is :",math.ceil(c))
print("The floor value is :",math.floor(c))
print("The sqrt value is :",math.sqrt(4))
print("The factorial value is :",math.factorial(3))

The ceiling value is : 10
The floor value is : 9
The sqrt value is : 2.0
The factorial value is : 6


In [7]:
#naive python mathematical functions
print("the maximum value is :",max(5,3,6))
print("the manimum value is :",min(5,3,6))
print("the rounded value is :",round(5.4))


the maximum value is : 6
the manimum value is : 3
the rounded value is : 5


In [8]:
#Random numbers
import random
#Generates floating point number between 0 and 1
print("Random number :",random.random())

#Generates random number within a range from 0 excluding upperbound
print("1.Range from list :",random.randrange(999))

#generate random number within a range from base value to range skipped
#Here the third term is skipped value which will not be printed. 
print("2.Range from list: ",random.randrange(2,12,4))
      
#randint
#generate random number between two integer including both      
x=0
while x<10:
    print("3.Random Number :",random.randint(0,9))
    x=x+1
#choice
#generate a random value from list
print("4.The value is:",random.choice([1,-1,2,3,4]))
      
      

Random number : 0.20871007198595337
1.Range from list : 256
2.Range from list:  2
3.Random Number : 4
3.Random Number : 2
3.Random Number : 3
3.Random Number : 5
3.Random Number : 0
3.Random Number : 4
3.Random Number : 1
3.Random Number : 3
3.Random Number : 0
3.Random Number : 6
4.The value is: -1


In [22]:
#display the prime numbers between 1 and 20
print("2")
for i in range(3,21):
    f=0
    for j in range(2,i):
          if(i%j==0):
            f=1
    if(f==0):
        print(i)    
        
    




2
3
5
7
11
13
17
19


In [16]:
var="hello"
print(type(var))
print(id(var)) #id gives the address value where data is stored in the memory
var="h"
print(id(var))
var="hello"
print(id(var))
print(var)

<class 'str'>
2427259098704
2427173673424
2427259098704
hello


In [18]:
#String slicing
str="HelloWorld"
print("First character: ",str[0])
print("Last character: ",str[-1])
print("0 to 3rd character: ",str[:3])
print("2nd to 3rd character: ",str[1:5])
print("3rd to 3rd last character: ",str[2:-2])

First character:  H
Last character:  d
0 to 3rd character:  Hel
2nd to 3rd character:  ello
3rd to 3rd last character:  lloWor


In [28]:
#String membership test
str="HelloWorld"
if "a" in str:
    print("Character a is present in str")
else:
    print("Character a is not present in str")
    
if "a" not in str:
    print("Character a is not present in str")
else:
    print("Character a is present in str")
        

Character a is not present in str
Character a is not present in str


In [35]:
str1="Hello World"
print("The lenth of str:",len(str1))
print("String after stripping:",str1.strip())
print(len(str1.strip()))
str1="Hello,World,All"
print(str1.split(","))
#max split
print(str1.split(",",1)) # 1 gives the number of split  

str2="Hello World"
print(str2.count("l"))
print(str2.count("l",0,5)) #(0,5) is range for count 

str3="hello World"
print("Number or not :",str3.find("l",0,len(str1)))

str4="4"
print("Number or not :",str4.isdigit())

The lenth of str: 11
String after stripping: Hello World
11
['Hello', 'World', 'All']
['Hello', 'World,All']
3
2
Number or not : 2
Number or not : True


In [15]:
str="HELLO"
l=len(str)
for i in range(1,l+1):
    for j in range(i,l):
        print(end=" ")
    print(" ".join(str[:i]))
for i in range(1,l):
    for j in range(1,i+1):
        print(end=" ")
    print(" ".join(str[:l-1]))
    l-=1

    H
   H E
  H E L
 H E L L
H E L L O
 H E L L
  H E L
   H E
    H


In [7]:
str="HELLO"
for i in range(1,len(str)+1):
    print(str[:i])


H
HE
HEL
HELL
HELLO


In [47]:
str="HELLO"
for i in range(len(str),0,-1):
    print(str[:i])


HELLO
HELL
HEL
HE
H


In [97]:
s = "BINGO"
print(" ".join(s))

B I N G O


In [21]:
list1=[1,5,3,7,5]
print(list1)
print(list1[1])
print(len(list1))
print(list1[1:4])
for x in list1:
    print("the value in the list are",x)

#updating list
list1[2]=21
print("list after updation: ",list1)

[1, 5, 3, 7, 5]
5
5
[5, 3, 7]
the value in the list are 1
the value in the list are 5
the value in the list are 3
the value in the list are 7
the value in the list are 5
list after updation:  [1, 5, 21, 7, 5]


In [25]:
#adding elements at specific position in list
list1=[1,5,3,7,5]
list1.insert(2,101)
print("List after adding element at the 2nd index: ",list1)

list1=[1,5,3,7,5]
print("The length of list1 before addition is :",len(list1))
list1.append(102)
print("the length of list1 after addition is:",len(list1))
print(list1)

list1.append([110,111])
print(len(list1))
print(list1)

List after adding element at the 2nd index:  [1, 5, 101, 3, 7, 5]
The length of list1 before addition is : 5
the length of list1 after addition is: 6
[1, 5, 3, 7, 5, 102]
7
[1, 5, 3, 7, 5, 102, [110, 111]]


In [26]:
list1=[1,5,3,7,5]
print(len(list1))
list1.extend([900,991])
print("after extending",len(list1))
print("after extending",list1)

5
after extending 7
after extending [1, 5, 3, 7, 5, 900, 991]


In [29]:
#removing the value
list1=[1,5,3,7,5]
del list1[0]
print("list after deletion: ",list1)
list1.remove(7)
print("list after deletion: ",list1)

list after deletion [5, 3, 7, 5]
list after deletion [5, 3, 5]


In [31]:
#pop method
list1=[1,5,3,7,5]
var=list1.pop(0)
print("list after deletion",list1)
print("Removed value",var)

list after deletion [5, 3, 7, 5]
Removed value 1


In [33]:
#default sorting is in ascending order
#sorting list
list1=[1,5,3,7,5]
print(list1)
list1.sort()
print("sorting asc",list1)
list1.sort(reverse=True)
print("Sorting desc",list1)

[1, 5, 3, 7, 5]
sorting asc [1, 3, 5, 5, 7]
Sorting desc [7, 5, 5, 3, 1]


In [35]:
#creating list of lists
T=[[11,12,5,2],[15,6,10],[10,8,12,5],[12,15,8,6]]
print(T)
print(T[0])
print(T[1][2]) #It means 1st list of the 2nd index

[[11, 12, 5, 2], [15, 6, 10], [10, 8, 12, 5], [12, 15, 8, 6]]
[11, 12, 5, 2]
10


In [36]:
#printing 2-D list
T=[[11,12,5,2],[15,6,10],[10,8,12,5],[12,15,8,6]]
for r in T:     # r is the list
    for c in r:   # c is an int
        print(c,end=" ")
    print()

11 12 5 2 
15 6 10 
10 8 12 5 
12 15 8 6 


In [2]:
# write a python program to count the no of strings in a list whose length are greater than 4 and
# the 1st and last character are same

list1=["madam","hills","maam","abcda"]
count=0
for i in list1:
    l=len(i)
    if(l>4 and i[0]==i[-1]):
        count=count+1
print(count)

2


In [23]:
# Given a list of integers with some duplicate values, write a program to create a list of unique values from the previous list
list1=[1,2,3,4,5,5]
list1.sort()
list2=[]
for x in list1:
    if x not in list2:
        list2.append(x)
for x in list2:
    print(x,end=" ")    

1 2 3 4 5 

In [9]:
#list a create of all the odd no from 0 to 10
list=[]
for i in range(0,11):
    if i%2==1:
        list.append(i)
print(list)

oddlist=[x for x in range(11) if x%2!=0]
print(oddlist)

[1, 3, 5, 7, 9]
[1, 3, 5, 7, 9]


In [25]:
#Creating Dictionary
dict1={
    "st":"Sachin Tendulkar",
    "msd":"Mahendra singh Dhoni",
    "run":10000  }
print(dict1)
print(dict1["run"])
for x in dict1:
    print(x)
for x in dict1:
    print(dict1[x])
for x in dict1:
    print(x," : ",dict1[x])

dict1['sv']="Sourav Ganguly"
print(dict1)
dict1["run"]=34500
print(dict1["run"])
print(len(dict1))



{'st': 'Sachin Tendulkar', 'msd': 'Mahendra singh Dhoni', 'run': 10000}
10000
st
msd
run
Sachin Tendulkar
Mahendra singh Dhoni
10000
st  :  Sachin Tendulkar
msd  :  Mahendra singh Dhoni
run  :  10000
{'st': 'Sachin Tendulkar', 'msd': 'Mahendra singh Dhoni', 'run': 10000, 'sv': 'Sourav Ganguly'}
34500
4


In [26]:
#remove items from list
dict1={
    "st":"Sachin Tendulkar",
    "msd":"Mahendra singh Dhoni",
    "run":10000  }
print(dict1)
var=dict1.pop('run') 
print(dict1)
print(var)  
var1=dict1.popitem()
print(dict1)
print(var1)

{'st': 'Sachin Tendulkar', 'msd': 'Mahendra singh Dhoni', 'run': 10000}
{'st': 'Sachin Tendulkar', 'msd': 'Mahendra singh Dhoni'}
10000
{'st': 'Sachin Tendulkar'}
('msd', 'Mahendra singh Dhoni')


In [1]:
# Create a dictionary
# {1:1,2:4,3:10,4:16,5:15,11:121,20:400}
#display the count of elements whose key are between 1 and 10 and the values are the square of the keys
dict1={
    1:1,
    2:4,
    3:10,
    4:16,
    5:15,
    11:121,
    20:400
    }
count=0
for x in dict1:
    if x<10 and x**2==dict1[x]:
        count+=1
print(count)

3


In [45]:
list1=["Sunday","Monday","Tuesday","Wednesday","Thrusday","Friday","Saturday"]
list2=[x[:3] for x in list1]
print(list2)

['Sun', 'Mon', 'Tue', 'Wed', 'Thr', 'Fri', 'Sat']


In [1]:
#Creating tuples
tuple1=("Sachin","Sourav","Dhoni")
print(tuple1[0])
for x in tuple1:
    print(x)

Sachin
Sachin
Sourav
Dhoni


In [2]:
tup1=('physics','chemistry',1997,2000)
tup2=(1,2,3,4,5,6,7)
print("tup1[0]: ",tup1[0])
print("tup2[1:5]: ",tup2[1:5])

tup1[0]:  physics
tup2[1:5]:  (2, 3, 4, 5)


In [23]:
import numpy as np
#1D array
arr1=np.array([1,2,3])
print(arr1)
print(type(arr1))
print(arr1.dtype)
print(arr1[0])

[1 2 3]
<class 'numpy.ndarray'>
int32
1


In [5]:
#nD array
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)
print(arr2[0,1])
print(arr2.ndim)

[[1 2 3]
 [4 5 6]]
2
2


In [6]:
arr2=np.array([(9),(2)])
print(arr2)
print(arr2.ndim)
#print(arr2[0,2])
arr2=np.array([(9,),(2,)])
print(arr2)
print(arr2.ndim)

[9 2]
1
[[9]
 [2]]
2


In [7]:
import numpy as np
#Data types
arr3=np.array([9,2],dtype=float)
print(arr3)
print(arr3.dtype)

[9. 2.]
float64


In [8]:
#shape-returns tupke consisting of array dimensions
arr1=np.array([[10,20],[30,40],[30,40]])
print("array shape is:",arr1.shape)
print("array is:",arr1)

array shape is: (3, 2)
array is: [[10 20]
 [30 40]
 [30 40]]


In [9]:
#resizes the shape
arr1=np.array([[10,20,40],[50,30,40]])
print("Array shape is :",arr1.shape)
arr1.shape=(3,2)
print("Array shape is :",arr1.shape)
print("Array is :",arr1)

Array shape is : (2, 3)
Array shape is : (3, 2)
Array is : [[10 20]
 [40 50]
 [30 40]]


In [10]:
#resizes the shape
arr2=np.array([[10,20,30,40],[50,30,40,80]])
b=arr2.reshape(4,2)
print("Array shape is:",arr2.shape)
print("Array is:",b)

Array shape is: (2, 4)
Array is: [[10 20]
 [30 40]
 [50 30]
 [40 80]]


In [11]:
arr2=np.empty([3,2],dtype=int)
print("Filled with random values:",arr2)#filled with random values

arr3=np.zeros([3,2])
print("Filled with 0 floats:",arr3)#default datatype is float

arr4=np.zeros([3,2],dtype=int)
print("Filled with 0 ints:",arr4)

arr5=np.ones([3,2],dtype=int)
print("Filled with 1 ints:",arr5)

Filled with random values: [[10 20]
 [30 40]
 [30 40]]
Filled with 0 floats: [[0. 0.]
 [0. 0.]
 [0. 0.]]
Filled with 0 ints: [[0 0]
 [0 0]
 [0 0]]
Filled with 1 ints: [[1 1]
 [1 1]
 [1 1]]


In [12]:
#Create an ndarray from a list
list1=[(1,2,3),(4,5,6)]
arr4=np.array(list1)
print("Dimension of array:",arr4.ndim)
print("Array from List of tuples:",arr4)

Dimension of array: 2
Array from List of tuples: [[1 2 3]
 [4 5 6]]


In [13]:
import numpy as np
arr1=np.arange(10)#upper bound not included
print(arr1)
arr2=np.arange(10,dtype=float)
print(arr2)

arr3=np.arange(2,10,2)
print(arr3)#start,stop,step

#linespace--instead of step, the no. of inteval is specified.
arr4=np.linspace(2,10,4)#endpoint is to included the upper bound or not
print("Upper bound included: ",arr4)

arr4=np.linspace(2,10,3,endpoint=False,dtype=int)
print("upper bound not included",arr4)

[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[2 4 6 8]
Upper bound included:  [ 2.          4.66666667  7.33333333 10.        ]
upper bound not included [2 4 7]


In [14]:

arr1=np.arange(10)

print("2.After slicing:",arr1[2:9:1])
print("3.After slicing:",arr1[2:])

#slicing for nd array
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2[:,1:])

2.After slicing: [2 3 4 5 6 7 8]
3.After slicing: [2 3 4 5 6 7 8 9]
[[2 3]
 [5 6]
 [8 9]]


In [15]:
#using ellipsis- means will consider all the list
arr4=np.array([[1,2,3,4],[4,5,6,10],[7,8,9,11]])
print(arr4[...,1])
print(arr4[2,...])
print(arr4[...,1:])

[2 5 8]
[ 7  8  9 11]
[[ 2  3  4]
 [ 5  6 10]
 [ 8  9 11]]


In [16]:
arr5=np.array([[1,2,3],[4,5,6],[7,8,9]])
y=arr5[[0,1,2],[1,0,2]] #(0,1),(1,0),(2,2)
print("8.After Slicing:",y)

8.After Slicing: [2 4 9]


In [17]:
#Broadcasting when operations of multiple arrays with shape
arr7=np.array([[10,20,30],[2,3,4]])
arr8=np.array([[40,30,20],[7,6,5]])
print("Multiplication on arrays of same shape:",arr7*arr8)

#Smaller array are broadcasted to larger array

arr8=np.array([[1,1,1],[20,30,40],[50,60,70]])
arr9=np.array([1,2,3])
print("Array after addition",arr8+arr9)

Multiplication on arrays of same shape: [[400 600 600]
 [ 14  18  20]]
Array after addition [[ 2  3  4]
 [21 32 43]
 [51 62 73]]


In [18]:
#transposing array and then iterating
tempdeftransposed=arr1.T
print("4. Transposed array:",tempdeftransposed)

4. Transposed array: [0 1 2 3 4 5 6 7 8 9]


In [19]:
#Concatenate
arr1=np.array([[2,3],[4,5]])
arr2=np.array([[6,7],[8,9]])
resarr=np.concatenate((arr1,arr2))#default axis=0
print("Concatenate along 0 axis:",resarr)
resarr=np.concatenate((arr1,arr2),axis=1)
print("Concatenate along 1 axis:",resarr)

Concatenate along 0 axis: [[2 3]
 [4 5]
 [6 7]
 [8 9]]
Concatenate along 1 axis: [[2 3 6 7]
 [4 5 8 9]]


In [20]:
#Split
arr3=np.arange(9)
print("Whole array:",arr3)
arr4=np.split(arr3,3)
print("After splitting in 3 equal sized axis:",arr4)

Whole array: [0 1 2 3 4 5 6 7 8]
After splitting in 3 equal sized axis: [array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [21]:
#Append elements
arr4=np.arange(9)
arr4=arr4.reshape(3,3)
print("Before appending:",arr4)
arr5=np.append(arr4,[10,11,12])
print("After appending:",arr5)
arr6=np.append(arr4,[[10,11,12],[13,14,15],[16,17,18]],axis=1)
print("Appended at axis 1:",arr6)
arr6=np.append(arr4,[[10,11,12]],axis=0)
print("Appended at 0 axis:",arr6)

Before appending: [[0 1 2]
 [3 4 5]
 [6 7 8]]
After appending: [ 0  1  2  3  4  5  6  7  8 10 11 12]
Appended at axis 1: [[ 0  1  2 10 11 12]
 [ 3  4  5 13 14 15]
 [ 6  7  8 16 17 18]]
Appended at 0 axis: [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [10 11 12]]


In [22]:
#insert at specific location
arr4=np.arange(9)
arr4=arr4.reshape(3,3)
print("Arr4",arr4)
arr7=np.insert(arr4,3,199)
print("Axis parameter not passed hence flattend:",arr7)
arr8=np.insert(arr4,3,[11],axis=0)
print("Inserted at 3rd index in 0 axis:",arr8)
arr9=np.insert(arr4,3,[290],axis=1)
print("Inserted at 3rd index in 1 axis:",arr9)

Arr4 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Axis parameter not passed hence flattend: [  0   1   2 199   3   4   5   6   7   8]
Inserted at 3rd index in 0 axis: [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [11 11 11]]
Inserted at 3rd index in 1 axis: [[  0   1   2 290]
 [  3   4   5 290]
 [  6   7   8 290]]


In [1]:
#Remove
import numpy as np
arr4=np.arange(9)
arr4=arr4.reshape(3,3)
arr10=np.delete(arr4,3)
print("Array flattend before deleting as axis parameter not passed:",arr10)
arr11=np.delete(arr4,2,axis=0)
print("Element deleted along 0 axis:",arr11)
print(arr4)
arr11=np.delete(arr4,2,axis=1)
print("Element deleted along 1 axis:",arr11)
print(arr4)

Array flattend before deleting as axis parameter not passed: [0 1 2 4 5 6 7 8]
Element deleted along 0 axis: [[0 1 2]
 [3 4 5]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Element deleted along 1 axis: [[0 1]
 [3 4]
 [6 7]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [2]:
#methods::np.add(arr,arr),np.subtract(arr,arr),np.multiply(arr,arr),np.divide(arr,arr),np.power(x,y),np.median(arr3.axis=0)

In [3]:
#sorting according to 
arr1=np.array([[12,14,17],[2,5,8],[15,20,21]])
arr2=np.mean(arr1,axis=1)
arr2=np.sort(arr2)
for i in arr2:
    for j in arr1:
        if np.mean(j)==i:
            print(j)

[2 5 8]
[12 14 17]
[15 20 21]


In [3]:
import numpy as np
import pandas as pd
#Series is a single dimensional labelled array, can hold any type
ser1=pd.Series([1,2,3])
print("the series is :\n",ser1)
arr1=np.array([1,2,3])
ser2=pd.Series(arr1)
print(ser2)

the series is :
 0    1
1    2
2    3
dtype: int64
0    1
1    2
2    3
dtype: int32


In [4]:
arr2=np.array([1,2,3])
ser3=pd.Series(arr2, index=['a','b','c'])
print("the series from ndarray is :\n",ser3)

the series from ndarray is :
 a    1
b    2
c    3
dtype: int32


In [5]:
dict1={'a':10,'b':20,'c':30}
ser3=pd.Series(dict1)
print("series from dictionary in the same order :",ser3)

series from dictionary in the same order : a    10
b    20
c    30
dtype: int64


In [6]:
dict1={'a':10,'b':20,'c':30}
ser4=pd.Series(dict1,index=['b','a','c'])
print(ser4)

b    20
a    10
c    30
dtype: int64


In [7]:
arr3=np.arange(0,4)
ser7=pd.Series(arr3,index=['a','b','c','d'])
print("the 2nd element is th series is :",ser7[1])
print("last 3 element of the series :",ser7[-3:])
print(ser7[-3:])

the 2nd element is th series is : 1
last 3 element of the series : b    1
c    2
d    3
dtype: int32
b    1
c    2
d    3
dtype: int32


In [8]:
df1=pd.DataFrame()
print("empty df :",df1)

empty df : Empty DataFrame
Columns: []
Index: []


In [9]:
#Create df from single list
list1=[1,2,3,4]
df2=pd.DataFrame(list1)
print(df2)

   0
0  1
1  2
2  3
3  4


In [10]:
list2=[[1,2,3],[4,5,6],[7,8,9]]
df3=pd.DataFrame(list2)
print(df3)

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9


In [11]:
#Create df from list of lists with defined column names  
list3=[['sachin',10000],['msd',20000],['virat',5000]]
df4=pd.DataFrame(list3,columns=['cricketer','runs'])
print("df from list of lists:\n",df4)
#df4["cricketer"].describe()
#print(df4.dtypes)
df4.info()
df4["runs"].describe()
df4["cricketer"].describe()

df from list of lists:
   cricketer   runs
0    sachin  10000
1       msd  20000
2     virat   5000
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
cricketer    3 non-null object
runs         3 non-null int64
dtypes: int64(1), object(1)
memory usage: 128.0+ bytes


count       3
unique      3
top       msd
freq        1
Name: cricketer, dtype: object

In [12]:
dict1={"name":['sachin','sourav','sachin'],"runs":[10000,20000,40000]}
df5=pd.DataFrame(dict1)
print(df5)

     name   runs
0  sachin  10000
1  sourav  20000
2  sachin  40000


In [13]:
dict1={"name":['sachin','sourav','sachin'],"runs":[10000,20000,40000]}
df5=pd.DataFrame(dict1,index=["rank1","rank2","rank3"])
print(df5)

         name   runs
rank1  sachin  10000
rank2  sourav  20000
rank3  sachin  40000


In [14]:
list3=[{"name":"sachin","run":20000},{"name":"sachin","run":20000,"address":"kolkata"}]
df6=pd.DataFrame(list3)
print(df6)

   address    name    run
0      NaN  sachin  20000
1  kolkata  sachin  20000


In [47]:
list4=[{"a":1,"b":2},{"a":4,"b":5},{"c":10}]
df7=pd.DataFrame(list4)
print("df from list of dict :\n",df7)
df8=pd.DataFrame(list4,columns=['a','d'])
print(df8)

df from list of dict :
      a    b     c
0  1.0  2.0   NaN
1  4.0  5.0   NaN
2  NaN  NaN  10.0
     a   d
0  1.0 NaN
1  4.0 NaN
2  NaN NaN


In [48]:
#create df from dict of series
data={"one":pd.Series([1,2,3],index=['a','b','c']),"two":pd.Series([1,2,3,4],index=['a','b','c','d'])}
df8=pd.DataFrame(data)
print("df from dict of series",df8)


df from dict of series    one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4


In [49]:
#select
data={"one":pd.Series([1,2,3],index=['a','b','c']),"two":pd.Series([1,2,3,4],index=['a','b','c','d'])}
df8=pd.DataFrame(data)
print("df from dict of series \n",df8)
df8["three"]=pd.Series([10,11,12],index=['a','b','c'])
print("df8 after adding \n",df8)
#add new cols with existing cols
df8["four"]=df8["one"]+df8["three"]
print("df after adding column: \n",df8)

df from dict of series 
    one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4
df8 after adding 
    one  two  three
a  1.0    1   10.0
b  2.0    2   11.0
c  3.0    3   12.0
d  NaN    4    NaN
df after adding column: 
    one  two  three  four
a  1.0    1   10.0  11.0
b  2.0    2   11.0  13.0
c  3.0    3   12.0  15.0
d  NaN    4    NaN   NaN


In [50]:
#renaming the column index
df8.rename(columns={'one':'One','two':'Two'},inplace=True)
print(df8)

   One  Two  three  four
a  1.0    1   10.0  11.0
b  2.0    2   11.0  13.0
c  3.0    3   12.0  15.0
d  NaN    4    NaN   NaN


In [51]:
#Delete column
print("Deleting the third column: \n")
del df8["three"]
print(df8)

Deleting the third column: 

   One  Two  four
a  1.0    1  11.0
b  2.0    2  13.0
c  3.0    3  15.0
d  NaN    4   NaN


In [52]:
#.loc[] is used for labes(a,b......) and #.iloc is used for indexes(0,1,2,3,......)

In [53]:
#Row Selection
print(df8.loc["b":"c"])

   One  Two  four
b  2.0    2  13.0
c  3.0    3  15.0


In [54]:
#Index Based
#Select only Rows
print(df8.iloc[0:3])
#Select rows and columns 
print(df8.iloc[[1,2,3],[1,2]])
#Slicing operator
print(df8.iloc[1:3,0:2])
print(df8.iloc[0:3,[1,2]])
#lable based
print(df8.loc['a':'c','One':'four'])
print(df8.loc[['a','b'],['One','four']])
print(df8.loc['a':'c',['One','four']])

   One  Two  four
a  1.0    1  11.0
b  2.0    2  13.0
c  3.0    3  15.0
   Two  four
b    2  13.0
c    3  15.0
d    4   NaN
   One  Two
b  2.0    2
c  3.0    3
   Two  four
a    1  11.0
b    2  13.0
c    3  15.0
   One  Two  four
a  1.0    1  11.0
b  2.0    2  13.0
c  3.0    3  15.0
   One  four
a  1.0  11.0
b  2.0  13.0
   One  four
a  1.0  11.0
b  2.0  13.0
c  3.0  15.0


In [55]:
#Append row
tempdf=pd.DataFrame([[99,98,97],[78,76,91]],columns=["One","Two","four"])
df8=df8.append(tempdf)
#df8.append(tempdf,inplace=True)
print("After appending 2 rows row: \n",df8)

After appending 2 rows row: 
     One  Two  four
a   1.0    1  11.0
b   2.0    2  13.0
c   3.0    3  15.0
d   NaN    4   NaN
0  99.0   98  97.0
1  78.0   76  91.0


In [56]:
print(df8.loc[0])

One     99.0
Two     98.0
four    97.0
Name: 0, dtype: float64


In [57]:
print(df8.iloc[0])

One      1.0
Two      1.0
four    11.0
Name: a, dtype: float64


In [58]:
#Deletion of row
df8=df8.drop("a")
df8=df8.drop(df8.index[0])
print("After deleting 1st row: \n",df8)

After deleting 1st row: 
     One  Two  four
c   3.0    3  15.0
d   NaN    4   NaN
0  99.0   98  97.0
1  78.0   76  91.0


In [61]:
#size
print("The length of the dataframe is :",df8.size)
#top rows
print("The top 2 rows are :\n",df8.head(5))

#bottom 2 rows
print("The bottom 2 rows are :\n",df8.tail(2))

The length of the dataframe is : 12
The top 2 rows are :
     One  Two  four
c   3.0    3  15.0
d   NaN    4   NaN
0  99.0   98  97.0
1  78.0   76  91.0
The bottom 2 rows are :
     One  Two  four
0  99.0   98  97.0
1  78.0   76  91.0


In [67]:
#Data manipulation in dataframe
emp=pd.read_csv("Employee.csv")
empdf=pd.DataFrame(emp)
print(empdf)

    subho   bhaduri
0  rcciit       NaN
1    ravi       NaN


In [68]:
x=empdf[['ename','job','mgr']]
print(x)
#1
tempdf=empdf.loc[empdf["deptno"]==30]
print(tempdf)

KeyError: "None of [Index(['ename', 'job', 'mgr'], dtype='object')] are in the [columns]"

In [ ]:
#2
tempdf1=empdf.loc[(empdf["sal"]>800) & (empdf["deptno"]==30)]
print(tempdf1[["ename","sal","deptno"]])